<h2 align='center' style='color:blue'>Dropout Regularization In Deep Neural Network</h2>

- In Deep learning, to avoid model over-fitting, we uses Dropout Regularization method.
- Randomly dropping few neurons/Hidden units from overfit models hidden layer, this method is called Dropout Regularization.

This is a dataset that describes sonar chirp returns bouncing off different services. The 60 input variables are the strength of the returns at different angles. It is a **binary classification problem** that requires a model to differentiate rocks from metal cylinders.

- Here Output has category as metal and rocks

Dataset information: https://archive.ics.uci.edu/ml/datasets/Connectionist+Bench+(Sonar,+Mines+vs.+Rocks)
Download it from here: https://archive.ics.uci.edu/ml/machine-learning-databases/undocumented/connectionist-bench/sonar/sonar.all-data

https://www.youtube.com/watch?v=lcI8ukTUEbo&list=PLeo1K3hjS3uu7CxAacxVndI4bE_o3BDtO&index=20

In [31]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [32]:
import warnings
warnings.filterwarnings('ignore')

In [33]:
df = pd.read_csv("./sonar_dataset.csv", header=None)
df.sample(5)

,0,1,2,3,4,5,6,7,8,9,...,51,52,53,54,55,56,57,58,59,60
22,0.0099,0.0484,0.0299,0.0297,0.0652,0.1077,0.2363,0.2385,0.0075,0.1882,...,0.0173,0.0149,0.0115,0.0202,0.0139,0.0029,0.0160,0.0106,0.0134,R
81,0.0100,0.0194,0.0155,0.0489,0.0839,0.1009,0.1627,0.2071,0.2696,0.2990,...,0.0130,0.0073,0.0077,0.0075,0.0060,0.0080,0.0019,0.0053,0.0019,R
144,0.0299,0.0688,0.0992,0.1021,0.0800,0.0629,0.0130,0.0813,0.1761,0.0998,...,0.0459,0.0277,0.0172,0.0087,0.0046,0.0203,0.0130,0.0115,0.0015,M
200,0.0131,0.0387,0.0329,0.0078,0.0721,0.1341,0.1626,0.1902,0.2610,0.3193,...,0.0150,0.0076,0.0032,0.0037,0.0071,0.0040,0.0009,0.0015,0.0085,M
126,0.0715,0.0849,0.0587,0.0218,0.0862,0.1801,0.1916,0.1896,0.2960,0.4186,...,0.0153,0.0121,0.0096,0.0196,0.0042,0.0066,0.0099,0.0083,0.0124,M

In [34]:
df.shape

(208, 61)

In [35]:
# check for nan values
df.isna().sum()

0     0
1     0
2     0
3     0
4     0
     ..
56    0
57    0
58    0
59    0
60    0
Length: 61, dtype: int64

In [36]:
df.columns

Int64Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
            17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
            34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
            51, 52, 53, 54, 55, 56, 57, 58, 59, 60],
           dtype='int64')

In [37]:
df[60].value_counts() # label is not skewed

M    111
R     97
Name: 60, dtype: int64

> Here 111 are metal and 97 are Rocks actegory and equally distributed

In [38]:
X = df.drop(60, axis=1)
y = df[60]
y.head()

0    R
1    R
2    R
3    R
4    R
Name: 60, dtype: object

In [39]:
#Convert category to numeric by onehot encoding
y = pd.get_dummies(y, drop_first=True)
y.sample(5) # R --> 1 and M --> 0

     R
23   1
192  0
111  0
141  0
106  0

In [40]:
type(y)

pandas.core.frame.DataFrame

In [41]:
y['R'].value_counts()

0    111
1     97
Name: R, dtype: int64

In [42]:
X.head()

,0,1,2,3,4,5,6,7,8,9,...,50,51,52,53,54,55,56,57,58,59
0,0.0200,0.0371,0.0428,0.0207,0.0954,0.0986,0.1539,0.1601,0.3109,0.2111,...,0.0232,0.0027,0.0065,0.0159,0.0072,0.0167,0.0180,0.0084,0.0090,0.0032
1,0.0453,0.0523,0.0843,0.0689,0.1183,0.2583,0.2156,0.3481,0.3337,0.2872,...,0.0125,0.0084,0.0089,0.0048,0.0094,0.0191,0.0140,0.0049,0.0052,0.0044
2,0.0262,0.0582,0.1099,0.1083,0.0974,0.2280,0.2431,0.3771,0.5598,0.6194,...,0.0033,0.0232,0.0166,0.0095,0.0180,0.0244,0.0316,0.0164,0.0095,0.0078
3,0.0100,0.0171,0.0623,0.0205,0.0205,0.0368,0.1098,0.1276,0.0598,0.1264,...,0.0241,0.0121,0.0036,0.0150,0.0085,0.0073,0.0050,0.0044,0.0040,0.0117
4,0.0762,0.0666,0.0481,0.0394,0.0590,0.0649,0.1209,0.2467,0.3564,0.4459,...,0.0156,0.0031,0.0054,0.0105,0.0110,0.0015,0.0072,0.0048,0.0107,0.0094

## Train test split

In [43]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=1)

In [44]:
X_train.head()

,0,1,2,3,4,5,6,7,8,9,...,50,51,52,53,54,55,56,57,58,59
67,0.0368,0.0403,0.0317,0.0293,0.0820,0.1342,0.1161,0.0663,0.0155,0.0506,...,0.0058,0.0091,0.0160,0.0160,0.0081,0.0070,0.0135,0.0067,0.0078,0.0068
14,0.0124,0.0433,0.0604,0.0449,0.0597,0.0355,0.0531,0.0343,0.1052,0.2120,...,0.0078,0.0083,0.0057,0.0174,0.0188,0.0054,0.0114,0.0196,0.0147,0.0062
164,0.0163,0.0198,0.0202,0.0386,0.0752,0.1444,0.1487,0.1484,0.2442,0.2822,...,0.0027,0.0077,0.0026,0.0031,0.0083,0.0020,0.0084,0.0108,0.0083,0.0033
179,0.0394,0.0420,0.0446,0.0551,0.0597,0.1416,0.0956,0.0802,0.1618,0.2558,...,0.0118,0.0146,0.0040,0.0114,0.0032,0.0062,0.0101,0.0068,0.0053,0.0087
19,0.0126,0.0149,0.0641,0.1732,0.2565,0.2559,0.2947,0.4110,0.4983,0.5920,...,0.0153,0.0092,0.0035,0.0098,0.0121,0.0006,0.0181,0.0094,0.0116,0.0063

# Using Deep Learning Model

## Model without Dropout Layer

In [45]:
import tensorflow as tf
from tensorflow import keras

In [46]:
# Here 60,30,15 ouput dim are randomly selected,last 1 is the actual based on output req. 
#Here op is binary result, so chose 1 hidden unit as o/p

model = keras.Sequential([
    keras.layers.Dense(60, input_dim=60, activation='relu'),
    keras.layers.Dense(30, activation='relu'),
    keras.layers.Dense(15, activation='relu'),
    keras.layers.Dense(1, activation='sigmoid')
])

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
# as its binary classification problem we have used 'binary_crossentropy'

model.fit(X_train, y_train, epochs=100, batch_size=8)  # Here used Mini batch Gradient Descent with batch size=8

Epoch 1/100
20/20 [==============================] - 1s 2ms/step - loss: 0.6843 - accuracy: 0.5385
Epoch 2/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6595 - accuracy: 0.6474
Epoch 3/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6398 - accuracy: 0.6859
Epoch 4/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6109 - accuracy: 0.7756
Epoch 5/100
20/20 [==============================] - 0s 2ms/step - loss: 0.5776 - accuracy: 0.7821
Epoch 6/100
20/20 [==============================] - 0s 2ms/step - loss: 0.5431 - accuracy: 0.7949
Epoch 7/100
20/20 [==============================] - 0s 2ms/step - loss: 0.5087 - accuracy: 0.7821
Epoch 8/100
20/20 [==============================] - 0s 2ms/step - loss: 0.4740 - accuracy: 0.7692
Epoch 9/100
20/20 [==============================] - 0s 2ms/step - loss: 0.4624 - accuracy: 0.8077
Epoch 10/100
20/20 [==============================] - 0s 2ms/step - loss: 0.4342 - accuracy: 0.8333
Epoch 11/100
20/20 [==============================] - 0s 2ms/step - loss: 0.4179 - accuracy: 0.8397
Epoch 12/100
20/20 [==============================] - 0s 2ms/step - loss: 0.3865 - accuracy: 0.8397
Epoch 13/100
20/20 [==============================] - 0s 2ms/step - loss: 0.3781 - accuracy: 0.8333
Epoch 14/100
20/20 [==============================] - 0s 2ms/step - loss: 0.3555 - accuracy: 0.8462
Epoch 15/100
20/20 [==============================] - 0s 2ms/step - loss: 0.3376 - accuracy: 0.8718
Epoch 16/100
20/20 [==============================] - 0s 2ms/step - loss: 0.3695 - accuracy: 0.8462
Epoch 17/100
20/20 [==============================] - 0s 2ms/step - loss: 0.3381 - accuracy: 0.8590
Epoch 18/100
20/20 [==============================] - 0s 2ms/step - loss: 0.3436 - accuracy: 0.8333
Epoch 19/100
20/20 [==============================] - 0s 4ms/step - loss: 0.3055 - accuracy: 0.8846
Epoch 20/100
20/20 [==============================] - 0s 4ms/step - loss: 0.2884 - accuracy: 0.8910
Epoch 21/100
20/20 [==============================] - 0s 4ms/step - loss: 0.2868 - accuracy: 0.9295
Epoch 22/100
20/20 [==============================] - 0s 5ms/step - loss: 0.2735 - accuracy: 0.9295
Epoch 23/100
20/20 [==============================] - 0s 5ms/step - loss: 0.2607 - accuracy: 0.9167
Epoch 24/100
20/20 [==============================] - 0s 2ms/step - loss: 0.2644 - accuracy: 0.8974
Epoch 25/100
20/20 [==============================] - 0s 2ms/step - loss: 0.2649 - accuracy: 0.8846
Epoch 26/100
20/20 [==============================] - 0s 2ms/step - loss: 0.2505 - accuracy: 0.9167
Epoch 27/100
20/20 [==============================] - 0s 2ms/step - loss: 0.2281 - accuracy: 0.9359
Epoch 28/100
20/20 [==============================] - 0s 2ms/step - loss: 0.2146 - accuracy: 0.9615
Epoch 29/100
20/20 [==============================] - 0s 2ms/step - loss: 0.2235 - accuracy: 0.9359
Epoch 30/100
20/20 [==============================] - 0s 2ms/step - loss: 0.2004 - accuracy: 0.9615
Epoch 31/100
20/20 [==============================] - 0s 2ms/step - loss: 0.1957 - accuracy: 0.9487
Epoch 32/100
20/20 [==============================] - 0s 2ms/step - loss: 0.1975 - accuracy: 0.9359
Epoch 33/100
20/20 [==============================] - 0s 2ms/step - loss: 0.1752 - accuracy: 0.9615
Epoch 34/100
20/20 [==============================] - 0s 2ms/step - loss: 0.1764 - accuracy: 0.9615
Epoch 35/100
20/20 [==============================] - 0s 2ms/step - loss: 0.1703 - accuracy: 0.9744
Epoch 36/100
20/20 [==============================] - 0s 2ms/step - loss: 0.2068 - accuracy: 0.9167
Epoch 37/100
20/20 [==============================] - 0s 2ms/step - loss: 0.1945 - accuracy: 0.9295
Epoch 38/100
20/20 [==============================] - 0s 2ms/step - loss: 0.1612 - accuracy: 0.9487
Epoch 39/100
20/20 [==============================] - 0s 2ms/step - loss: 0.1925 - accuracy: 0.9103
Epoch 40/100
20/20 [==============================] - 0s 2ms/step - loss: 0.1631 - accuracy: 0.9551
Epoch 41/100
20/20 [==============================] - 0s 2ms/step - loss: 0.1466 - accuracy: 0.9679
Epoch 42/100
20/20 [==============================] - 0s 2ms/step - loss: 0.1316 - accuracy: 0.9679
Epoch 43/100
20/20 [==============================] - 0s 2ms/step - loss: 0.1510 - accuracy: 0.9487
Epoch 44/100
20/20 [==============================] - 0s 2ms/step - loss: 0.1361 - accuracy: 0.9551
Epoch 45/100
20/20 [==============================] - 0s 2ms/step - loss: 0.1103 - accuracy: 0.9744
Epoch 46/100
20/20 [==============================] - 0s 2ms/step - loss: 0.1226 - accuracy: 0.9679
Epoch 47/100
20/20 [==============================] - 0s 2ms/step - loss: 0.1163 - accuracy: 0.9744
Epoch 48/100
20/20 [==============================] - 0s 2ms/step - loss: 0.1120 - accuracy: 0.9615
Epoch 49/100
20/20 [==============================] - 0s 2ms/step - loss: 0.1126 - accuracy: 0.9744
Epoch 50/100
20/20 [==============================] - 0s 2ms/step - loss: 0.0875 - accuracy: 0.9744
Epoch 51/100
20/20 [==============================] - 0s 2ms/step - loss: 0.0820 - accuracy: 0.9808
Epoch 52/100
20/20 [==============================] - 0s 2ms/step - loss: 0.0872 - accuracy: 0.9679
Epoch 53/100
20/20 [==============================] - 0s 2ms/step - loss: 0.0842 - accuracy: 0.9679
Epoch 54/100
20/20 [==============================] - 0s 2ms/step - loss: 0.0698 - accuracy: 0.9808
Epoch 55/100
20/20 [==============================] - 0s 2ms/step - loss: 0.0706 - accuracy: 0.9744
Epoch 56/100
20/20 [==============================] - 0s 2ms/step - loss: 0.0622 - accuracy: 0.9872
Epoch 57/100
20/20 [==============================] - 0s 2ms/step - loss: 0.0638 - accuracy: 0.9808
Epoch 58/100
20/20 [==============================] - 0s 3ms/step - loss: 0.0532 - accuracy: 0.9872
Epoch 59/100
20/20 [==============================] - 0s 3ms/step - loss: 0.0493 - accuracy: 0.9872
Epoch 60/100
20/20 [==============================] - 0s 3ms/step - loss: 0.0437 - accuracy: 0.9936
Epoch 61/100
20/20 [==============================] - 0s 2ms/step - loss: 0.0405 - accuracy: 0.9936
Epoch 62/100
20/20 [==============================] - 0s 2ms/step - loss: 0.0393 - accuracy: 0.9936
Epoch 63/100
20/20 [==============================] - 0s 2ms/step - loss: 0.0338 - accuracy: 1.0000
Epoch 64/100
20/20 [==============================] - 0s 2ms/step - loss: 0.0300 - accuracy: 0.9936
Epoch 65/100
20/20 [==============================] - 0s 2ms/step - loss: 0.0286 - accuracy: 1.0000
Epoch 66/100
20/20 [==============================] - 0s 2ms/step - loss: 0.0431 - accuracy: 1.0000
Epoch 67/100
20/20 [==============================] - 0s 2ms/step - loss: 0.1022 - accuracy: 0.9615
Epoch 68/100
20/20 [==============================] - 0s 2ms/step - loss: 0.0492 - accuracy: 0.9936
Epoch 69/100
20/20 [==============================] - 0s 2ms/step - loss: 0.0317 - accuracy: 0.9936
Epoch 70/100
20/20 [==============================] - 0s 3ms/step - loss: 0.0246 - accuracy: 0.9936
Epoch 71/100
20/20 [==============================] - 0s 2ms/step - loss: 0.0209 - accuracy: 1.0000
Epoch 72/100
20/20 [==============================] - 0s 2ms/step - loss: 0.0165 - accuracy: 1.0000
Epoch 73/100
20/20 [==============================] - 0s 3ms/step - loss: 0.0161 - accuracy: 1.0000
Epoch 74/100
20/20 [==============================] - 0s 2ms/step - loss: 0.0151 - accuracy: 1.0000
Epoch 75/100
20/20 [==============================] - 0s 2ms/step - loss: 0.0144 - accuracy: 1.0000
Epoch 76/100
20/20 [==============================] - 0s 2ms/step - loss: 0.0127 - accuracy: 1.0000
Epoch 77/100
20/20 [==============================] - 0s 2ms/step - loss: 0.0117 - accuracy: 1.0000
Epoch 78/100
20/20 [==============================] - 0s 2ms/step - loss: 0.0110 - accuracy: 1.0000
Epoch 79/100
20/20 [==============================] - 0s 2ms/step - loss: 0.0101 - accuracy: 1.0000
Epoch 80/100
20/20 [==============================] - 0s 2ms/step - loss: 0.0096 - accuracy: 1.0000
Epoch 81/100
20/20 [==============================] - 0s 3ms/step - loss: 0.0088 - accuracy: 1.0000
Epoch 82/100
20/20 [==============================] - 0s 2ms/step - loss: 0.0084 - accuracy: 1.0000
Epoch 83/100

20/20 [==============================] - 0s 3ms/step - loss: 0.0081 - accuracy: 1.0000
Epoch 84/100
20/20 [==============================] - 0s 2ms/step - loss: 0.0079 - accuracy: 1.0000
Epoch 85/100
20/20 [==============================] - 0s 2ms/step - loss: 0.0107 - accuracy: 1.0000
Epoch 86/100
20/20 [==============================] - 0s 2ms/step - loss: 0.0095 - accuracy: 1.0000
Epoch 87/100
20/20 [==============================] - 0s 2ms/step - loss: 0.0103 - accuracy: 1.0000
Epoch 88/100
20/20 [==============================] - 0s 2ms/step - loss: 0.0105 - accuracy: 1.0000
Epoch 89/100
20/20 [==============================] - 0s 2ms/step - loss: 0.0064 - accuracy: 1.0000
Epoch 90/100
20/20 [==============================] - 0s 2ms/step - loss: 0.0052 - accuracy: 1.0000
Epoch 91/100
20/20 [==============================] - 0s 2ms/step - loss: 0.0051 - accuracy: 1.0000
Epoch 92/100
20/20 [==============================] - 0s 2ms/step - loss: 0.0055 - accuracy: 1.0000
Epoch 93/100
20/20 [==============================] - 0s 2ms/step - loss: 0.0044 - accuracy: 1.0000
Epoch 94/100
20/20 [==============================] - 0s 2ms/step - loss: 0.0046 - accuracy: 1.0000
Epoch 95/100
20/20 [==============================] - 0s 2ms/step - loss: 0.0041 - accuracy: 1.0000
Epoch 96/100
20/20 [==============================] - 0s 2ms/step - loss: 0.0040 - accuracy: 1.0000
Epoch 97/100
20/20 [==============================] - 0s 2ms/step - loss: 0.0037 - accuracy: 1.0000
Epoch 98/100
20/20 [==============================] - 0s 2ms/step - loss: 0.0037 - accuracy: 1.0000
Epoch 99/100
20/20 [==============================] - 0s 2ms/step - loss: 0.0036 - accuracy: 1.0000
Epoch 100/100
20/20 [==============================] - 0s 2ms/step - loss: 0.0033 - accuracy: 1.0000

In [47]:
model.evaluate(X_test, y_test)

2/2 [==============================] - 0s 2ms/step - loss: 1.0624 - accuracy: 0.7692

[1.0624363422393799, 0.7692307829856873]

> Here accuracy of train data  =1 , but with test data its 0.7692 --> So this looks like overfit model

Training Accuracy >>> Test Accuracy

In [48]:
y_pred = model.predict(X_test).reshape(-1)
print(y_pred[:10])

# round the values to nearest integer ie 0 or 1
y_pred = np.round(y_pred)
print(y_pred[:10])

[1.7055223e-06 9.8673832e-01 9.9651957e-01 8.0421785e-05 1.0000000e+00
 9.9961841e-01 3.7274331e-02 1.0000000e+00 4.3368340e-04 1.0000000e+00]
[0. 1. 1. 0. 1. 1. 0. 1. 0. 1.]

In [49]:
y_test[:10]

     R
186  0
155  0
165  0
200  0
58   1
34   1
151  0
18   1
202  0
62   1

In [50]:
from sklearn.metrics import confusion_matrix , classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.74      0.85      0.79        27
           1       0.81      0.68      0.74        25

    accuracy                           0.77        52
   macro avg       0.78      0.77      0.77        52
weighted avg       0.77      0.77      0.77        52

### Model with Dropout Layer
- Here dropout applied after each layer, here 0.5 means 50% hiddenunits are dropped randomly

In [51]:
modeld = keras.Sequential([
    keras.layers.Dense(60, input_dim=60, activation='relu'),
    keras.layers.Dropout(0.5), 
    keras.layers.Dense(30, activation='relu'),
    keras.layers.Dropout(0.5),
    keras.layers.Dense(15, activation='relu'),
    keras.layers.Dropout(0.5),
    keras.layers.Dense(1, activation='sigmoid')
])

modeld.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

modeld.fit(X_train, y_train, epochs=100, batch_size=8)

Epoch 1/100
20/20 [==============================] - 1s 2ms/step - loss: 0.7823 - accuracy: 0.4551
Epoch 2/100
20/20 [==============================] - 0s 2ms/step - loss: 0.7161 - accuracy: 0.5513
Epoch 3/100
20/20 [==============================] - 0s 2ms/step - loss: 0.7046 - accuracy: 0.4872
Epoch 4/100
20/20 [==============================] - 0s 2ms/step - loss: 0.7161 - accuracy: 0.4808
Epoch 5/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6998 - accuracy: 0.4744
Epoch 6/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6910 - accuracy: 0.5705
Epoch 7/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6965 - accuracy: 0.5000
Epoch 8/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6827 - accuracy: 0.5962
Epoch 9/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6975 - accuracy: 0.5128
Epoch 10/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6836 - accuracy: 0.5192
Epoch 11/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6893 - accuracy: 0.5641
Epoch 12/100
20/20 [==============================] - 0s 3ms/step - loss: 0.6948 - accuracy: 0.5385
Epoch 13/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6659 - accuracy: 0.5705
Epoch 14/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6838 - accuracy: 0.5449
Epoch 15/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6817 - accuracy: 0.5513
Epoch 16/100
20/20 [==============================] - 0s 2ms/step - loss: 0.7015 - accuracy: 0.5064
Epoch 17/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6868 - accuracy: 0.5256
Epoch 18/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6843 - accuracy: 0.5641
Epoch 19/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6907 - accuracy: 0.5449
Epoch 20/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6963 - accuracy: 0.5577
Epoch 21/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6735 - accuracy: 0.5833
Epoch 22/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6856 - accuracy: 0.5385
Epoch 23/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6890 - accuracy: 0.5513
Epoch 24/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6596 - accuracy: 0.6026
Epoch 25/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6892 - accuracy: 0.5513
Epoch 26/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6839 - accuracy: 0.5321
Epoch 27/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6610 - accuracy: 0.5833
Epoch 28/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6648 - accuracy: 0.5769
Epoch 29/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6659 - accuracy: 0.6026
Epoch 30/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6913 - accuracy: 0.5833
Epoch 31/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6703 - accuracy: 0.5769
Epoch 32/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6446 - accuracy: 0.6795
Epoch 33/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6582 - accuracy: 0.6346
Epoch 34/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6255 - accuracy: 0.6731
Epoch 35/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6220 - accuracy: 0.6667
Epoch 36/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6458 - accuracy: 0.6282
Epoch 37/100
20/20 [==============================] - 0s 3ms/step - loss: 0.6805 - accuracy: 0.5962
Epoch 38/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6173 - accuracy: 0.6667
Epoch 39/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6254 - accuracy: 0.6603
Epoch 40/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6437 - accuracy: 0.6090
Epoch 41/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6245 - accuracy: 0.6538
Epoch 42/100
20/20 [==============================] - 0s 2ms/step - loss: 0.5995 - accuracy: 0.6795
Epoch 43/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6202 - accuracy: 0.6538
Epoch 44/100
20/20 [==============================] - 0s 3ms/step - loss: 0.6567 - accuracy: 0.6154
Epoch 45/100
20/20 [==============================] - 0s 3ms/step - loss: 0.6069 - accuracy: 0.6667
Epoch 46/100
20/20 [==============================] - 0s 3ms/step - loss: 0.5853 - accuracy: 0.6923
Epoch 47/100
20/20 [==============================] - 0s 3ms/step - loss: 0.6201 - accuracy: 0.6603
Epoch 48/100
20/20 [==============================] - 0s 3ms/step - loss: 0.5685 - accuracy: 0.7308
Epoch 49/100
20/20 [==============================] - 0s 3ms/step - loss: 0.5723 - accuracy: 0.6923
Epoch 50/100
20/20 [==============================] - 0s 3ms/step - loss: 0.5730 - accuracy: 0.6923
Epoch 51/100
20/20 [==============================] - 0s 3ms/step - loss: 0.5537 - accuracy: 0.7244
Epoch 52/100
20/20 [==============================] - 0s 3ms/step - loss: 0.5447 - accuracy: 0.7244
Epoch 53/100
20/20 [==============================] - 0s 3ms/step - loss: 0.5025 - accuracy: 0.7372
Epoch 54/100
20/20 [==============================] - 0s 3ms/step - loss: 0.5400 - accuracy: 0.7821
Epoch 55/100
20/20 [==============================] - 0s 3ms/step - loss: 0.5250 - accuracy: 0.7244
Epoch 56/100
20/20 [==============================] - 0s 3ms/step - loss: 0.5207 - accuracy: 0.7756
Epoch 57/100
20/20 [==============================] - 0s 3ms/step - loss: 0.4981 - accuracy: 0.7628
Epoch 58/100
20/20 [==============================] - 0s 3ms/step - loss: 0.5594 - accuracy: 0.7244
Epoch 59/100
20/20 [==============================] - 0s 3ms/step - loss: 0.4975 - accuracy: 0.7436
Epoch 60/100
20/20 [==============================] - 0s 3ms/step - loss: 0.4551 - accuracy: 0.8077
Epoch 61/100
20/20 [==============================] - 0s 3ms/step - loss: 0.5193 - accuracy: 0.7692
Epoch 62/100
20/20 [==============================] - 0s 3ms/step - loss: 0.4481 - accuracy: 0.7692
Epoch 63/100
20/20 [==============================] - 0s 3ms/step - loss: 0.4937 - accuracy: 0.7628
Epoch 64/100
20/20 [==============================] - 0s 3ms/step - loss: 0.4693 - accuracy: 0.7628
Epoch 65/100
20/20 [==============================] - 0s 3ms/step - loss: 0.4402 - accuracy: 0.7821
Epoch 66/100
20/20 [==============================] - 0s 3ms/step - loss: 0.4598 - accuracy: 0.8269
Epoch 67/100
20/20 [==============================] - 0s 3ms/step - loss: 0.4089 - accuracy: 0.8141
Epoch 68/100
20/20 [==============================] - 0s 3ms/step - loss: 0.4564 - accuracy: 0.7949
Epoch 69/100
20/20 [==============================] - 0s 3ms/step - loss: 0.4430 - accuracy: 0.8141
Epoch 70/100
20/20 [==============================] - 0s 3ms/step - loss: 0.3888 - accuracy: 0.8526
Epoch 71/100
20/20 [==============================] - 0s 3ms/step - loss: 0.4493 - accuracy: 0.7885
Epoch 72/100
20/20 [==============================] - 0s 3ms/step - loss: 0.4198 - accuracy: 0.7885
Epoch 73/100
20/20 [==============================] - 0s 3ms/step - loss: 0.4213 - accuracy: 0.8013
Epoch 74/100
20/20 [==============================] - 0s 3ms/step - loss: 0.4380 - accuracy: 0.8077
Epoch 75/100
20/20 [==============================] - 0s 3ms/step - loss: 0.4136 - accuracy: 0.8205
Epoch 76/100
20/20 [==============================] - 0s 3ms/step - loss: 0.4033 - accuracy: 0.8013
Epoch 77/100
20/20 [==============================] - 0s 3ms/step - loss: 0.3801 - accuracy: 0.8333
Epoch 78/100
20/20 [==============================] - 0s 3ms/step - loss: 0.4096 - accuracy: 0.8205
Epoch 79/100
20/20 [==============================] - 0s 3ms/step - loss: 0.4105 - accuracy: 0.8333
Epoch 80/100
20/20 [==============================] - 0s 3ms/step - loss: 0.3551 - accuracy: 0.8462
Epoch 81/100
20/20 [==============================] - 0s 3ms/step - loss: 0.3650 - accuracy: 0.8782
Epoch 82/100
20/20 [==============================] - 0s 3ms/step - loss: 0.3888 - accuracy: 0.8782
Epoch 83/100

20/20 [==============================] - 0s 3ms/step - loss: 0.4180 - accuracy: 0.8077
Epoch 84/100
20/20 [==============================] - 0s 3ms/step - loss: 0.3279 - accuracy: 0.8974
Epoch 85/100
20/20 [==============================] - 0s 4ms/step - loss: 0.3618 - accuracy: 0.8333
Epoch 86/100
20/20 [==============================] - 0s 4ms/step - loss: 0.4141 - accuracy: 0.8526
Epoch 87/100
20/20 [==============================] - 0s 4ms/step - loss: 0.3950 - accuracy: 0.8462
Epoch 88/100
20/20 [==============================] - 0s 2ms/step - loss: 0.3936 - accuracy: 0.8462
Epoch 89/100
20/20 [==============================] - 0s 2ms/step - loss: 0.3676 - accuracy: 0.8462
Epoch 90/100
20/20 [==============================] - 0s 2ms/step - loss: 0.3935 - accuracy: 0.8333
Epoch 91/100
20/20 [==============================] - 0s 2ms/step - loss: 0.3330 - accuracy: 0.8526
Epoch 92/100
20/20 [==============================] - 0s 2ms/step - loss: 0.3429 - accuracy: 0.8718
Epoch 93/100
20/20 [==============================] - 0s 2ms/step - loss: 0.4183 - accuracy: 0.8397
Epoch 94/100
20/20 [==============================] - 0s 2ms/step - loss: 0.3612 - accuracy: 0.8526
Epoch 95/100
20/20 [==============================] - 0s 2ms/step - loss: 0.2904 - accuracy: 0.8910
Epoch 96/100
20/20 [==============================] - 0s 2ms/step - loss: 0.2550 - accuracy: 0.9038
Epoch 97/100
20/20 [==============================] - 0s 2ms/step - loss: 0.3730 - accuracy: 0.8654
Epoch 98/100
20/20 [==============================] - 0s 2ms/step - loss: 0.2811 - accuracy: 0.9167
Epoch 99/100
20/20 [==============================] - 0s 2ms/step - loss: 0.2972 - accuracy: 0.8910
Epoch 100/100
20/20 [==============================] - 0s 2ms/step - loss: 0.3630 - accuracy: 0.8269

In [52]:
modeld.evaluate(X_test, y_test)

2/2 [==============================] - 0s 4ms/step - loss: 0.4615 - accuracy: 0.7692

[0.4615395665168762, 0.7692307829856873]

> Here accuracy of train data  = 0.8269 , and with test data its 0.7692 --> So this looks like NOT overfit model, both accuracy are almost nearer

- So this dropout helped to reduce overfit problem. This mainly used in computer vision, where complex neural network with high overfit problem

Training Accuracy is still good but Test Accuracy Improved

In [53]:
y_pred = modeld.predict(X_test).reshape(-1)
print(y_pred[:10])

# round the values to nearest integer ie 0 or 1
y_pred = np.round(y_pred)
print(y_pred[:10])

[4.0942430e-04 8.5563195e-01 9.3275410e-01 3.1206548e-02 9.9641812e-01
 8.9563310e-01 2.8651327e-01 9.9556708e-01 5.7962388e-02 9.9812460e-01]
[0. 1. 1. 0. 1. 1. 0. 1. 0. 1.]

In [54]:
from sklearn.metrics import confusion_matrix , classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.76      0.81      0.79        27
           1       0.78      0.72      0.75        25

    accuracy                           0.77        52
   macro avg       0.77      0.77      0.77        52
weighted avg       0.77      0.77      0.77        52

**You can see that by using dropout layer test accuracy increased from 0.75 to 0.77**
- Here dropout applied randomly only random hidden units, so accuracy will be different in each run